### ISSUE TITLE
Use URLEncoder and drop ring-codec dependency

### ISSUE THREAD

**Issue by igrishaev** [jerben/clj-aws-sign#1]
Hi,

I'm a happy user of this library, it helped me a lot. One thing I wanted to discuss with you: are you OK if I try to replace `ring-codec/url-encode` with `URLEncoder/encode` call? The thing is, I'm concerned aboud dependencies and would like to have them as narrow as possible in my project. If yes, I can create a PR.

Ivan

**Comment by joseferben** [comment]
Hi @igrishaev, yes that makes a lot of sense. A PR would be very appreciated.
