### ISSUE TITLE
typo in recent merge

### ISSUE THREAD

**Issue by lowecg** [jerben/clj-aws-sign#3]
In the recent merge, 13c380847786c1b5c4e08975608ee86a6b15c779, the def has a typo. It should be `UNSIGNED_PAYLOAD`, not `UNSIGNED_PAYLOD`.

```
(def UNSIGNED_PAYLOD "UNSIGNED-PAYLOAD")
```

That was a timely commit, as I'd just hit the same issue with S3 presigning.

**Comment by joseferben** [comment]
thanks you! fixed in https://github.com/joseferben/clj-aws-sign/commit/b3f049b910f2b4d646f4c8182daec5991129534a
